version: '3.5'

x-main-db-enviroment: &main-db-environment
  MAIN_DB_HOST: main_db
  MAIN_DB_NAME: jibrel_db
  MAIN_DB_USER: postgres
  MAIN_DB_USER_PASSWORD: postgres

x-core: &core
  environment:
    <<: *main-db-environment
    PORT: 8080
    DJANGO_SECRET_KEY: secret
    CELERY_BROKER_URL: amqp://rabbit:rabbit@broker:5672//
    CMS_INTEGRATION_PRIVATE_KEY: secret
  depends_on:
    - main_db
    - broker

services:
  admin_db:
    image: postgres:11-alpine
    volumes:
      - admin_db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jibrel_admin_db

  main_db:
    image: postgres:11-alpine
    volumes:
      - main_db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jibrel_db

  broker:
    image: rabbitmq:3.7-alpine
    volumes:
      - broker-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit

  worker:
    <<: *core
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: production
    image: jibrelcom_backend/worker:latest
    command: celeryworker -Q default,onfido

  worker-email:
    <<: *core
    image: jibrelcom_backend/worker:latest
    command: celeryworker -Q email

  worker-twilio:
    <<: *core
    image: jibrelcom_backend/worker:latest
    command: celeryworker -Q twilio

  scheduler:
    <<: *core
    image: jibrelcom_backend/worker:latest
    depends_on:
      - main_db
      - broker
    command: celerybeat

  api:
    <<: *core
    image: jibrelcom_backend/worker:latest
    depends_on:
      - main_db
      - broker
      - worker
      - worker-email
      - worker-twilio
      - scheduler
    command: api

  admin:
    <<: *core
    image: jibrelcom_backend/worker:latest
    depends_on:
      - admin_db
      - main_db
      - broker
    restart: on-failure
    environment:
      <<: *main-db-environment
      DJANGO_SECRET_KEY: secret
      DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1
      ADMIN_DB_HOST: admin_db
      ADMIN_DB_NAME: jibrel_admin_db
      ADMIN_DB_USER: postgres
      ADMIN_DB_USER_PASSWORD: postgres
      ADMIN_DB_PORT: 5432
      PORT: 8000
      CELERY_BROKER_URL: amqp://rabbit:rabbit@broker:5672//
    command: admin

volumes:
  main_db-data:
  broker-data:
  admin_db-data:
