# Generated by Django 2.2.2 on 2019-11-26 13:05

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalServiceCallLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('initiator_type', models.CharField(choices=[('user', 'User'), ('anonymous', 'Anonymous user'), ('system', 'System')], max_length=20)),
                ('initiator_ip', models.GenericIPAddressField(null=True)),
                ('action_type', models.IntegerField(choices=[(1, 'Phone verification code sending'), (2, 'Phone verification code checking'), (3, 'Send mail')])),
                ('kwargs', django.contrib.postgres.fields.jsonb.JSONField()),
                ('request_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('response_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('processed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
