# Generated by Django 2.2.2 on 2019-11-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
    ]
