# Generated by Django 2.2.2 on 2019-12-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20191126_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalservicecalllog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('error', 'Error')], default='success', max_length=32),
        ),
    ]
