# Generated by Django 2.2.2 on 2019-12-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_externalservicecalllog_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalservicecalllog',
            options={'ordering': ['-created_at']},
        ),
    ]
