# Generated by Django 3.0.3 on 2020-02-27 09:28

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_banking', '0005_auto_20200207_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositCardOperation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_banking.operation',),
        ),
        migrations.CreateModel(
            name='RefundCardOperation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_banking.operation',),
        ),
        migrations.CreateModel(
            name='WithdrawalCardOperation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_banking.operation',),
        ),
    ]
