# Generated by Django 2.2.2 on 2020-01-23 14:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_auto_20200122_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='id',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(editable=False, max_length=42, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
