# Generated by Django 2.2.2 on 2020-01-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_auto_20200123_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
