# Generated by Django 3.0.3 on 2020-03-05 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_banking', '0006_auto_20200304_1455'),
        migrations.swappable_dependency(settings.DJANGO_BANKING_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCheckoutAccount',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=30, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_banking.Account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_account', to=settings.DJANGO_BANKING_USER_MODEL)),
            ],
            options={
                'db_table': 'django_banking_checkoutaccount',
            },
        ),
        migrations.CreateModel(
            name='CheckoutCharge',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('charge_id', models.CharField(db_index=True, max_length=30, null=True)),
                ('payment_status', models.CharField(choices=[('authorized', 'authorized'), ('pending', 'pending'), ('card verified', 'verified'), ('captured', 'captured'), ('declined', 'declined'), ('paid', 'paid')], max_length=30)),
                ('redirect_link', models.URLField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charge_checkout', to='django_banking.Operation')),
            ],
            options={
                'db_table': 'django_banking_checkoutcharge',
            },
        ),
    ]
