# Generated by Django 3.0.3 on 2020-03-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutcharge',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'pending'), ('authorized', 'authorized'), ('card verified', 'card verified'), ('voided', 'voided'), ('partially captured', 'partially captured'), ('captured', 'captured'), ('partially refunded', 'partially refunded'), ('refunded', 'refunded'), ('cancelled', 'cancelled'), ('declined', 'declined'), ('paid', 'paid')], max_length=30),
        ),
    ]
