# Generated by Django 3.0.3 on 2020-03-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200305_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutcharge',
            name='charge_id',
            field=models.CharField(db_index=True, default=1, max_length=30),
            preserve_default=False,
        ),
    ]
