# Generated by Django 3.0.3 on 2020-03-15 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20200312_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutcharge',
            options={'ordering': ['-created_at']},
        ),
    ]
