# Generated by Django 2.2.2 on 2019-11-26 13:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import jibrel.core.storages
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('verification_sid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('expired', 'Expired'), ('max_attempts_reached', 'Max attempts reached'), ('canceled', 'Canceled')], max_length=1200)),
                ('task_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_requests', to='authentication.Phone')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneVerificationCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField()),
                ('failed', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='kyc.PhoneVerification')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file', models.FileField(storage=jibrel.core.storages.AmazonS3Storage(location='kyc'), upload_to='')),
                ('checksum', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('residency_visa', 'Residency visa')], max_length=20)),
                ('side', models.CharField(choices=[('front', 'Front side'), ('back', 'Back side')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BasicKYCSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship', models.CharField(max_length=2)),
                ('residency', models.CharField(max_length=2)),
                ('first_name', models.CharField(max_length=320)),
                ('middle_name', models.CharField(blank=True, max_length=320)),
                ('last_name', models.CharField(max_length=320)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_date_hijri', models.CharField(blank=True, max_length=32, null=True)),
                ('personal_id_type', models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID')], max_length=20)),
                ('personal_id_number', models.CharField(max_length=20)),
                ('personal_id_doe', models.DateField(blank=True, null=True)),
                ('personal_id_doe_hijri', models.CharField(blank=True, max_length=32, null=True)),
                ('residency_visa_number', models.CharField(max_length=20, null=True)),
                ('residency_visa_doe', models.DateField(blank=True, null=True)),
                ('residency_visa_doe_hijri', models.CharField(blank=True, max_length=32, null=True)),
                ('onfido_applicant_id', models.CharField(max_length=100, null=True)),
                ('onfido_check_id', models.CharField(max_length=100, null=True)),
                ('onfido_result', models.CharField(choices=[('consider', 'Consider'), ('clear', 'Clear')], max_length=100, null=True)),
                ('onfido_report', models.FileField(null=True, storage=jibrel.core.storages.AmazonS3Storage(location='kyc'), upload_to='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_agreed_aml_policy', models.BooleanField()),
                ('is_birth_date_hijri', models.BooleanField(default=False)),
                ('is_confirmed_ubo', models.BooleanField()),
                ('is_personal_id_doe_hijri', models.BooleanField(default=False)),
                ('is_residency_visa_doe_hijri', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transitioned_at', models.DateTimeField()),
                ('admin_note', models.TextField(blank=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('personal_id_document_back', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kyc.Document')),
                ('personal_id_document_front', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kyc.Document')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.Profile')),
                ('residency_visa_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kyc.Document')),
            ],
        ),
    ]
