# Generated by Django 2.2.2 on 2019-12-03 10:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import jibrel.core.storages
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('verification_sid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('expired', 'Expired'), ('max_attempts_reached', 'Max attempts reached'), ('canceled', 'Canceled')], max_length=1200)),
                ('task_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_requests', to='authentication.Phone')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneVerificationCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField()),
                ('failed', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='kyc.PhoneVerification')),
            ],
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file', models.FileField(storage=jibrel.core.storages.AmazonS3Storage(location='kyc'), upload_to='')),
                ('checksum', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualKYCSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business')], max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transitioned_at', models.DateTimeField()),
                ('onfido_applicant_id', models.CharField(blank=True, max_length=100, null=True)),
                ('onfido_check_id', models.CharField(blank=True, max_length=100, null=True)),
                ('onfido_result', models.CharField(blank=True, choices=[('consider', 'Consider'), ('clear', 'Clear')], max_length=100, null=True)),
                ('onfido_report', models.FileField(null=True, storage=jibrel.core.storages.AmazonS3Storage(location='kyc'), upload_to='')),
                ('first_name', models.CharField(max_length=320)),
                ('middle_name', models.CharField(blank=True, max_length=320)),
                ('last_name', models.CharField(max_length=320)),
                ('birthDate', models.DateField()),
                ('nationality', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('steer_address', models.CharField(max_length=320)),
                ('apartment', models.CharField(blank=True, max_length=320)),
                ('city', models.CharField(max_length=320)),
                ('country', models.CharField(max_length=320)),
                ('occupation', models.CharField(choices=[('accounting', 'Accounting'), ('admin_clerical_automotive', 'Admin & ClericalAutomotive'), ('banking', 'Banking'), ('biotech', 'Biotech'), ('broadcast_journalism', 'Broadcast Journalism'), ('business_development', 'Business Development'), ('construction', 'Construction'), ('consultant', 'Consultant'), ('customer_service', 'Customer Service'), ('design', 'Design'), ('distribution_shipping', 'Distribution Shipping'), ('education_teaching', 'Education Teaching'), ('engineering', 'Engineering'), ('entry_level_new_grad', 'Entry Level New Grad'), ('executive', 'Executive'), ('facilities', 'Facilities'), ('finance', 'Finance'), ('franchise', 'Franchise'), ('general_business', 'General Business'), ('general_labor', 'General Labor'), ('government', 'Government'), ('grocery', 'Grocery'), ('health_care', 'Health Care'), ('hotel_hospitality', 'Hotel Hospitality'), ('human_resources', 'Human Resources'), ('information_technology', 'Information Technology'), ('installation_maint_repair', 'Installation Maint Repair'), ('insurance', 'Insurance'), ('inventory', 'Inventory'), ('legal', 'Legal'), ('legal_admin', 'Legal Admin'), ('management', 'Management'), ('manufacturing', 'Manufacturing'), ('marketing', 'Marketing'), ('media_journalism_newspaper', 'Media Journalism Newspaper'), ('nonprofit_social_services', 'Nonprofit Social Services'), ('nurse', 'Nurse'), ('pharmaceutical', 'Pharmaceutical'), ('professional_services', 'Professional Services'), ('purchasing_procurement', 'Purchasing Procurement'), ('qa_quality_control', 'QA Quality Control'), ('real_estate', 'Real Estate'), ('research', 'Research'), ('restaurant_food_service', 'Restaurant Food Service'), ('retail', 'Retail'), ('sales', 'Sales'), ('science', 'Science'), ('skilled_labor_trades', 'Skilled Labor Trades'), ('strategy_planning', 'Strategy Planning'), ('supply_chain', 'Supply Chain'), ('telecommunications', 'Telecommunications'), ('training', 'Training'), ('transportation', 'Transportation'), ('warehouse', 'Warehouse')], max_length=320)),
                ('occupation_other', models.CharField(max_length=320)),
                ('income_source', models.CharField(choices=[('primary_occupation', 'Primary Occupation'), ('secondary_business_activities', 'Secondary Business Activities'), ('sale_assets', 'Sale of Stock, Real Estate or Other Assets'), ('inheritance', 'Inheritance')], max_length=320)),
                ('income_source_other', models.CharField(max_length=320)),
                ('passport_number', models.CharField(max_length=320)),
                ('passport_expiration_date', models.DateField()),
                ('aml_agreed', models.BooleanField()),
                ('ubo_confirmed', models.BooleanField()),
                ('passport_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kyc.KYCDocument')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.Profile')),
                ('proof_of_address_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kyc.KYCDocument')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
