# Generated by Django 2.2.2 on 2019-11-28 11:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basickycsubmission',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='basickycsubmission',
            name='birth_date_hijri',
        ),
        migrations.RemoveField(
            model_name='basickycsubmission',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='basickycsubmission',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='basickycsubmission',
            name='is_agreed_aml_policy',
        ),
        migrations.RemoveField(
            model_name='basickycsubmission',
            name='is_birth_date_hijri',
        ),
        migrations.RemoveField(
            model_name='basickycsubmission',
            name='is_confirmed_ubo',
        ),
        migrations.RemoveField(
            model_name='basickycsubmission',
            name='is_personal_id_doe_hijri',
        ),
        migrations.RemoveField(
            model_name='basickycsubmission',
            name='is_residency_visa_doe_hijri',
        ),
        migrations.RemoveField(
            model_name='basickycsubmission',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='basickycsubmission',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='basickycsubmission',
            name='personal_id_document_back',
        ),
        migrations.RemoveField(
            model_name='basickycsubmission',
            name='personal_id_document_front',
        ),
        migrations.RemoveField(
            model_name='basickycsubmission',
            name='personal_id_doe',
        ),
        migrations.RemoveField(
            model_name='basickycsubmission',
            name='personal_id_doe_hijri',
        ),
        migrations.RemoveField(
            model_name='basickycsubmission',
            name='personal_id_number',
        ),
        migrations.RemoveField(
            model_name='basickycsubmission',
            name='personal_id_type',
        ),
        migrations.RemoveField(
            model_name='basickycsubmission',
            name='residency',
        ),
        migrations.RemoveField(
            model_name='basickycsubmission',
            name='residency_visa_document',
        ),
        migrations.RemoveField(
            model_name='basickycsubmission',
            name='residency_visa_doe',
        ),
        migrations.RemoveField(
            model_name='basickycsubmission',
            name='residency_visa_doe_hijri',
        ),
        migrations.RemoveField(
            model_name='basickycsubmission',
            name='residency_visa_number',
        ),
        migrations.AddField(
            model_name='basickycsubmission',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], default='personal', max_length=20),
        ),
        migrations.AddField(
            model_name='basickycsubmission',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basickycsubmission',
            name='schema',
            field=models.CharField(default='v1', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID')], max_length=20),
        ),
    ]
