# Generated by Django 2.2.2 on 2019-12-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualkycsubmission',
            old_name='birthDate',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='individualkycsubmission',
            old_name='steer_address',
            new_name='street_address',
        ),
        migrations.AlterField(
            model_name='individualkycsubmission',
            name='income_source',
            field=models.CharField(blank=True, choices=[('primary_occupation', 'Primary Occupation'), ('secondary_business_activities', 'Secondary Business Activities'), ('sale_assets', 'Sale of Stock, Real Estate or Other Assets'), ('inheritance', 'Inheritance')], max_length=320),
        ),
        migrations.AlterField(
            model_name='individualkycsubmission',
            name='income_source_other',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='individualkycsubmission',
            name='occupation',
            field=models.CharField(blank=True, choices=[('accounting', 'Accounting'), ('admin_clerical_automotive', 'Admin & ClericalAutomotive'), ('banking', 'Banking'), ('biotech', 'Biotech'), ('broadcast_journalism', 'Broadcast Journalism'), ('business_development', 'Business Development'), ('construction', 'Construction'), ('consultant', 'Consultant'), ('customer_service', 'Customer Service'), ('design', 'Design'), ('distribution_shipping', 'Distribution Shipping'), ('education_teaching', 'Education Teaching'), ('engineering', 'Engineering'), ('entry_level_new_grad', 'Entry Level New Grad'), ('executive', 'Executive'), ('facilities', 'Facilities'), ('finance', 'Finance'), ('franchise', 'Franchise'), ('general_business', 'General Business'), ('general_labor', 'General Labor'), ('government', 'Government'), ('grocery', 'Grocery'), ('health_care', 'Health Care'), ('hotel_hospitality', 'Hotel Hospitality'), ('human_resources', 'Human Resources'), ('information_technology', 'Information Technology'), ('installation_maint_repair', 'Installation Maint Repair'), ('insurance', 'Insurance'), ('inventory', 'Inventory'), ('legal', 'Legal'), ('legal_admin', 'Legal Admin'), ('management', 'Management'), ('manufacturing', 'Manufacturing'), ('marketing', 'Marketing'), ('media_journalism_newspaper', 'Media Journalism Newspaper'), ('nonprofit_social_services', 'Nonprofit Social Services'), ('nurse', 'Nurse'), ('pharmaceutical', 'Pharmaceutical'), ('professional_services', 'Professional Services'), ('purchasing_procurement', 'Purchasing Procurement'), ('qa_quality_control', 'QA Quality Control'), ('real_estate', 'Real Estate'), ('research', 'Research'), ('restaurant_food_service', 'Restaurant Food Service'), ('retail', 'Retail'), ('sales', 'Sales'), ('science', 'Science'), ('skilled_labor_trades', 'Skilled Labor Trades'), ('strategy_planning', 'Strategy Planning'), ('supply_chain', 'Supply Chain'), ('telecommunications', 'Telecommunications'), ('training', 'Training'), ('transportation', 'Transportation'), ('warehouse', 'Warehouse')], max_length=320),
        ),
        migrations.AlterField(
            model_name='individualkycsubmission',
            name='occupation_other',
            field=models.CharField(blank=True, max_length=320),
        ),
    ]
