# Generated by Django 2.2.2 on 2019-12-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualkycsubmission',
            name='income_source_other',
        ),
        migrations.RemoveField(
            model_name='individualkycsubmission',
            name='occupation_other',
        ),
        migrations.AlterField(
            model_name='individualkycsubmission',
            name='income_source',
            field=models.CharField(max_length=320),
        ),
        migrations.AlterField(
            model_name='individualkycsubmission',
            name='occupation',
            field=models.CharField(max_length=320),
        ),
    ]
