# Generated by Django 2.2.2 on 2019-12-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_auto_20191223_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationalkycsubmission',
            name='aml_agreed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisationalkycsubmission',
            name='ubo_confirmed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
