# Generated by Django 2.2.2 on 2019-12-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_auto_20191203_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualkycsubmission',
            name='transitioned_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
