# Generated by Django 2.2.2 on 2019-12-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_auto_20191203_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualkycsubmission',
            name='post_code',
            field=models.CharField(blank=True, max_length=320),
        ),
    ]
