# Generated by Django 2.2.2 on 2019-12-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_auto_20191223_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualkycsubmission',
            old_name='aml_agreed',
            new_name='is_agreed_risks',
        ),
        migrations.RenameField(
            model_name='organisationalkycsubmission',
            old_name='aml_agreed',
            new_name='is_agreed_risks',
        ),
        migrations.RemoveField(
            model_name='individualkycsubmission',
            name='ubo_confirmed',
        ),
        migrations.RemoveField(
            model_name='organisationalkycsubmission',
            name='ubo_confirmed',
        ),
    ]
