# Generated by Django 2.2.2 on 2019-12-23 13:45

from django.db import migrations, models
import jibrel.core.storages


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_auto_20191223_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='last_name',
            field=models.CharField(default='', max_length=320),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='onfido_applicant_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='onfido_check_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='onfido_report',
            field=models.FileField(null=True, storage=jibrel.core.storages.AmazonS3Storage(location='kyc'), upload_to=''),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='onfido_result',
            field=models.CharField(blank=True, choices=[('consider', 'Consider'), ('clear', 'Clear')], max_length=100, null=True),
        ),
    ]
