# Generated by Django 2.2.2 on 2019-12-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_auto_20191223_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basekycsubmission',
            name='onfido_result',
            field=models.CharField(blank=True, choices=[('consider', 'Consider'), ('clear', 'Clear'), ('unsupported', 'Unsupported')], max_length=100, null=True),
        ),
    ]
