# Generated by Django 2.2.2 on 2019-12-06 11:46

from django.db import migrations, models
import django.db.models.deletion
import jibrel.core.storages


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_individualkycsubmission_post_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseKYCSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business')], max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transitioned_at', models.DateTimeField(auto_now_add=True)),
                ('onfido_applicant_id', models.CharField(blank=True, max_length=100, null=True)),
                ('onfido_check_id', models.CharField(blank=True, max_length=100, null=True)),
                ('onfido_result', models.CharField(blank=True, choices=[('consider', 'Consider'), ('clear', 'Clear')], max_length=100, null=True)),
                ('onfido_report', models.FileField(null=True, storage=jibrel.core.storages.AmazonS3Storage(location='kyc'), upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='individualkycsubmission',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='individualkycsubmission',
            name='admin_note',
        ),
        migrations.RemoveField(
            model_name='individualkycsubmission',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='individualkycsubmission',
            name='id',
        ),
        migrations.RemoveField(
            model_name='individualkycsubmission',
            name='onfido_applicant_id',
        ),
        migrations.RemoveField(
            model_name='individualkycsubmission',
            name='onfido_check_id',
        ),
        migrations.RemoveField(
            model_name='individualkycsubmission',
            name='onfido_report',
        ),
        migrations.RemoveField(
            model_name='individualkycsubmission',
            name='onfido_result',
        ),
        migrations.RemoveField(
            model_name='individualkycsubmission',
            name='reject_reason',
        ),
        migrations.RemoveField(
            model_name='individualkycsubmission',
            name='status',
        ),
        migrations.RemoveField(
            model_name='individualkycsubmission',
            name='transitioned_at',
        ),
        migrations.AddField(
            model_name='individualkycsubmission',
            name='base_kyc',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='individual', serialize=False, to='kyc.BaseKYCSubmission'),
            preserve_default=False,
        ),
    ]
