# Generated by Django 2.2.2 on 2019-12-06 09:46

from django.db import migrations, models
import django.db.models.deletion
import jibrel.core.storages


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('kyc', '0004_individualkycsubmission_post_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=320)),
                ('trading_name', models.CharField(max_length=320)),
                ('date_of_incorporation', models.DateField()),
                ('place_of_incorporation', models.CharField(max_length=320)),
                ('articles_of_incorporation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kyc.KYCDocument')),
                ('commercial_register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kyc.KYCDocument')),
                ('shareholder_register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kyc.KYCDocument')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=320)),
                ('apartment', models.CharField(blank=True, max_length=320)),
                ('post_code', models.CharField(blank=True, max_length=320)),
                ('city', models.CharField(max_length=320)),
                ('country', models.CharField(max_length=320)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganisationalKYCSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=320)),
                ('apartment', models.CharField(blank=True, max_length=320)),
                ('post_code', models.CharField(blank=True, max_length=320)),
                ('city', models.CharField(max_length=320)),
                ('country', models.CharField(max_length=320)),
                ('account_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business')], max_length=20)),
                ('first_name', models.CharField(max_length=320)),
                ('middle_name', models.CharField(blank=True, max_length=320)),
                ('last_name', models.CharField(max_length=320)),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('passport_number', models.CharField(max_length=320)),
                ('passport_expiration_date', models.DateField()),
                ('admin_note', models.TextField(blank=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transitioned_at', models.DateTimeField(auto_now_add=True)),
                ('onfido_applicant_id', models.CharField(blank=True, max_length=100, null=True)),
                ('onfido_check_id', models.CharField(blank=True, max_length=100, null=True)),
                ('onfido_result', models.CharField(blank=True, choices=[('consider', 'Consider'), ('clear', 'Clear')], max_length=100, null=True)),
                ('onfido_report', models.FileField(null=True, storage=jibrel.core.storages.AmazonS3Storage(location='kyc'), upload_to='')),
                ('phone_number', models.CharField(max_length=320)),
                ('company_address_principal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kyc.OfficeAddress')),
                ('company_address_registered', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kyc.OfficeAddress')),
                ('company_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kyc.CompanyInfo')),
                ('passport_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kyc.KYCDocument')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.Profile')),
                ('proof_of_address_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kyc.KYCDocument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=320)),
                ('organisational_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='kyc.OrganisationalKYCSubmission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=320)),
                ('apartment', models.CharField(blank=True, max_length=320)),
                ('post_code', models.CharField(blank=True, max_length=320)),
                ('city', models.CharField(max_length=320)),
                ('country', models.CharField(max_length=320)),
                ('full_name', models.CharField(max_length=320)),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(max_length=320)),
                ('phone_number', models.CharField(max_length=320)),
                ('email', models.EmailField(max_length=254)),
                ('organisational_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='kyc.OrganisationalKYCSubmission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
