# Generated by Django 2.2.2 on 2019-12-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_individualkycsubmission_post_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualkycsubmission',
            name='email',
        ),
        migrations.AddField(
            model_name='individualkycsubmission',
            name='alias',
            field=models.CharField(blank=True, max_length=320),
        ),
    ]
