# Generated by Django 2.2.2 on 2019-12-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_auto_20191206_1146'),
        ('kyc', '0005_organisational_kyc_submission'),
    ]

    operations = [
    ]
