# Generated by Django 2.2.2 on 2019-12-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_auto_20191224_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualkycsubmission',
            old_name='is_agreed_risks',
            new_name='is_agreed_documents',
        ),
        migrations.RenameField(
            model_name='organisationalkycsubmission',
            old_name='is_agreed_risks',
            new_name='is_agreed_documents',
        ),
    ]
