# Generated by Django 2.2.2 on 2019-12-09 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0006_merge_20191209_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationalkycsubmission',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='organisationalkycsubmission',
            name='admin_note',
        ),
        migrations.RemoveField(
            model_name='organisationalkycsubmission',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='organisationalkycsubmission',
            name='id',
        ),
        migrations.RemoveField(
            model_name='organisationalkycsubmission',
            name='onfido_applicant_id',
        ),
        migrations.RemoveField(
            model_name='organisationalkycsubmission',
            name='onfido_check_id',
        ),
        migrations.RemoveField(
            model_name='organisationalkycsubmission',
            name='onfido_report',
        ),
        migrations.RemoveField(
            model_name='organisationalkycsubmission',
            name='onfido_result',
        ),
        migrations.RemoveField(
            model_name='organisationalkycsubmission',
            name='reject_reason',
        ),
        migrations.RemoveField(
            model_name='organisationalkycsubmission',
            name='status',
        ),
        migrations.RemoveField(
            model_name='organisationalkycsubmission',
            name='transitioned_at',
        ),
        migrations.AddField(
            model_name='organisationalkycsubmission',
            name='base_kyc',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='organisation', serialize=False, to='kyc.BaseKYCSubmission'),
            preserve_default=False,
        ),
    ]
