# Generated by Django 2.2.2 on 2019-12-25 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0006_auto_20191224_1449'),
        ('kyc', '0004_auto_20191223_1345'),
    ]

    operations = [
    ]
