# Generated by Django 2.2.2 on 2019-12-09 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0007_auto_20191209_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationalkycsubmission',
            name='company_info',
        ),
        migrations.AddField(
            model_name='organisationalkycsubmission',
            name='articles_of_incorporation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kyc.KYCDocument'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisationalkycsubmission',
            name='commercial_register',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kyc.KYCDocument'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisationalkycsubmission',
            name='company_name',
            field=models.CharField(default=None, max_length=320),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisationalkycsubmission',
            name='date_of_incorporation',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisationalkycsubmission',
            name='place_of_incorporation',
            field=models.CharField(default=None, max_length=320),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisationalkycsubmission',
            name='shareholder_register',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kyc.KYCDocument'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisationalkycsubmission',
            name='trading_name',
            field=models.CharField(default=None, max_length=320),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
    ]
