# Generated by Django 2.2.2 on 2019-12-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0007_merge_20191225_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='middle_name',
            field=models.CharField(blank=True, max_length=320),
        ),
    ]
