# Generated by Django 2.2.2 on 2019-12-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0008_beneficiary_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='onfido_result',
            field=models.CharField(blank=True, choices=[('consider', 'Consider'), ('clear', 'Clear'), ('unsupported', 'Unsupported')], max_length=100, null=True),
        ),
    ]
