# Generated by Django 2.2.2 on 2020-01-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0009_auto_20191225_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualkycsubmission',
            name='is_agreed_documents',
        ),
        migrations.RemoveField(
            model_name='organisationalkycsubmission',
            name='is_agreed_documents',
        ),
    ]
