# Generated by Django 2.2.2 on 2019-12-12 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0010_auto_20191210_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationalkycsubmission',
            name='company_address_principal',
        ),
        migrations.RemoveField(
            model_name='organisationalkycsubmission',
            name='company_address_registered',
        ),
        migrations.AddField(
            model_name='officeaddress',
            name='kyc_principal_here',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_address_principal', to='kyc.OrganisationalKYCSubmission'),
        ),
        migrations.AddField(
            model_name='officeaddress',
            name='kyc_registered_here',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_address_registered', to='kyc.OrganisationalKYCSubmission'),
        ),
    ]
