# Generated by Django 2.2.2 on 2019-12-13 10:31

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0011_auto_20191212_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='passport_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kyc.KYCDocument'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='passport_expiration_date',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='passport_number',
            field=models.CharField(default='', max_length=320),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='proof_of_address_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kyc.KYCDocument'),
            preserve_default=False,
        ),
    ]
