# Generated by Django 2.2.2 on 2019-12-13 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0011_auto_20191212_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationalkycsubmission',
            name='base_kyc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='business', serialize=False, to='kyc.BaseKYCSubmission'),
        ),
    ]
