# Generated by Django 2.2.2 on 2019-12-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0012_auto_20191213_1722'),
        ('kyc', '0012_auto_20191213_1031'),
    ]

    operations = [
    ]
