# Generated by Django 2.2.2 on 2019-12-25 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_banking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositWireTransferOperation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_banking.operation',),
        ),
        migrations.CreateModel(
            name='WithdrawalWireTransferOperation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_banking.operation',),
        ),
        migrations.CreateModel(
            name='UserBankAccount',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('swift_code', models.CharField(max_length=11)),
                ('bank_name', models.CharField(max_length=200)),
                ('holder_name', models.CharField(max_length=200)),
                ('iban_number', models.CharField(max_length=34)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_banking.Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'django_banking_userbankaccount',
            },
        ),
        migrations.CreateModel(
            name='ColdBankAccount',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('bank_account_details', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_banking.Account')),
            ],
            options={
                'db_table': 'django_banking_coldbankaccount',
            },
        ),
    ]
