# Generated by Django 2.2.2 on 2020-01-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wire_transfer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coldbankaccount',
            name='bank_account_details',
        ),
        migrations.AddField(
            model_name='coldbankaccount',
            name='account_number',
            field=models.CharField(default='AUTOCREATED', max_length=320),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coldbankaccount',
            name='bank_name',
            field=models.CharField(default='AUTOCREATED', max_length=320),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coldbankaccount',
            name='holder_name',
            field=models.CharField(default='AUTOCREATED', max_length=320),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coldbankaccount',
            name='iban_number',
            field=models.CharField(default='AUTOCREATED', max_length=320),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coldbankaccount',
            name='swift_code',
            field=models.CharField(default='AUTOCREATED', max_length=320),
            preserve_default=False,
        ),
    ]
