# Generated by Django 2.2.2 on 2020-01-21 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_banking', '0004_auto_20200120_1220'),
        ('wire_transfer', '0002_auto_20200116_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundWireTransferOperation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_banking.operation',),
        ),
    ]
