# Generated by Django 2.2.2 on 2020-02-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wire_transfer', '0003_refundwiretransferoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldbankaccount',
            name='branch_address',
            field=models.CharField(default='AUTOCREATED', max_length=320),
            preserve_default=False,
        ),
    ]
