# Generated by Django 2.2.2 on 2020-02-04 16:13

from django.db import migrations


def set_branch_address(apps, schema_editor):
    cba = apps.get_model('wire_transfer', 'ColdBankAccount')
    cba.objects.filter(
        account__asset__symbol__iexact='usd'
    ).update(
        branch_address="Cours de Rive 11, 1204 Genève, Switzerland"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('wire_transfer', '0004_coldbankaccount_branch_address'),
    ]

    operations = [
        migrations.RunPython(set_branch_address)
    ]
