# Generated by Django 2.2.2 on 2019-11-26 13:04

from django.db import migrations, models
import jibrel.authentication.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=320, unique=True)),
                ('is_email_confirmed', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('admin_note', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', jibrel.authentication.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OneTimeToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('checked', models.BooleanField(default=False)),
                ('operation_type', models.IntegerField(choices=[(1, 'Email verification'), (2, 'Password reset activate'), (3, 'Password reset'), (4, 'Crypto withdrawal confirmation')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5)),
                ('number', models.CharField(max_length=26)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('is_agreed_terms', models.BooleanField(default=False)),
                ('is_agreed_privacy_policy', models.BooleanField(default=False)),
                ('kyc_status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('advanced', 'Advanced verification')], default='unverified', max_length=20)),
                ('risk_level', models.CharField(blank=True, choices=[(None, 'Default'), ('tier1', 'Tier 1'), ('tier2', 'Tier 2'), ('tier3', 'Tier 3')], default=None, max_length=10, null=True)),
                ('language', models.CharField(blank=True, max_length=2)),
                ('tap_customer_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
