# Generated by Django 2.2.2 on 2019-12-19 20:56

from django.db import migrations, models
import jibrel.authentication.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=320, unique=True)),
                ('is_email_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admin_note', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', jibrel.authentication.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OneTimeToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('checked', models.BooleanField(default=False)),
                ('operation_type', models.IntegerField(choices=[(1, 'Email verification'), (2, 'Password reset activate'), (3, 'Password reset'), (4, 'Crypto withdrawal confirmation')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('unconfirmed', 'Unconfirmed'), ('code_requested', 'Code requested'), ('code_sent', 'Code sent'), ('code_submitted', 'Code submitted'), ('code_incorrect', 'Code incorrect'), ('expired', 'Expired'), ('max_attempts_reached', 'Max attempts reached'), ('verified', 'Verified')], default='unconfirmed', max_length=320)),
                ('code_requested_at', models.DateTimeField(null=True)),
                ('code_submitted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_agreed_terms', models.BooleanField(default=False)),
                ('is_agreed_privacy_policy', models.BooleanField(default=False)),
                ('kyc_status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('advanced', 'Advanced verification')], default='unverified', max_length=20)),
                ('language', models.CharField(blank=True, max_length=2)),
            ],
        ),
    ]
