# Generated by Django 2.2.2 on 2019-12-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20191219_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('unverified', 'Unverified'), ('verified', 'Verified'), ('advanced', 'Advanced verification')], default='unverified', max_length=20),
        ),
    ]
