# Generated by Django 2.2.2 on 2019-12-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20191206_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='phone',
            name='code_requested_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='code_submitted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='status',
            field=models.CharField(choices=[('unconfirmed', 'Unconfirmed'), ('code_requested', 'Code requested'), ('code_sent', 'Code sent'), ('code_submitted', 'Code submitted'), ('code_incorrect', 'Code incorrect'), ('expired', 'Expired'), ('max_attempts_reached', 'Max attempts reached'), ('verified', 'Verified')], default='unconfirmed', max_length=320),
        ),
    ]
