# Generated by Django 2.2.2 on 2019-12-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20191211_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='code',
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(max_length=32),
        ),
    ]
