# Generated by Django 3.0 on 2020-02-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20191224_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='is_primary',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
