# Generated by Django 3.0 on 2020-02-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_phone_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
