# Generated by Django 2.2.2 on 2019-12-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20191211_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_blocked',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
