# Generated by Django 3.0.3 on 2020-02-07 14:41

from django.db import migrations
from django.db.models import Q, Count


def fix_is_primary(apps, schema_editor):
    Profile = apps.get_model('authentication', 'Profile')
    qs = Profile.objects.annotate(
        primary_phones=Count('phones', filter=Q(phones__is_primary=True))
    ).filter(
        primary_phones__gt=1
    )
    # if no any actions applied by the admin
    # only the latest phone can be primary at the moment
    for obj in qs:
        obj.phones.exclude(
            uuid=obj.phones.latest('created_at').uuid
        ).update(is_primary=False)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20200203_1558'),
    ]

    operations = [
        migrations.RunPython(fix_is_primary)
    ]
