# Generated by Django 2.2.2 on 2019-12-26 11:56

from django.db import migrations

DATA = [
    # fiats
    {
        'uuid': 'ec261b1e-0e9f-4d58-a4c9-3d42a63252b7',
        'name': 'United States Dollar',
        'symbol': 'USD',
        'type': 'fiat'
    }
]


def insert_initial_assets(apps, schema_editor):
    Asset = apps.get_model('django_banking', 'Asset')
    for asset_data in DATA:
        Asset.objects.create(**asset_data)


class Migration(migrations.Migration):

    dependencies = [
        ('django_banking', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_initial_assets)
    ]
