# Generated by Django 3.0.3 on 2020-03-05 10:44

from django.db import migrations


def set_operations_method(apps, schema_editor):
    from django_banking.models.transactions.enum import OperationType
    from django_banking.models.transactions.enum import OperationMethod
    Operation = apps.get_model('django_banking', 'Operation')
    Operation.objects.filter(
        type=OperationType.DEPOSIT
    ).update(
        method=OperationMethod.WIRE_TRANSFER
    )


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_operations_method),
    ]
