# Generated by Django 3.0.3 on 2020-03-12 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_banking', '0006_auto_20200304_1455'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFoloosiAccount',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_banking.Account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='foloosi_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'django_banking_foloosiaccount',
            },
        ),
        migrations.CreateModel(
            name='FoloosiCharge',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('charge_id', models.CharField(db_index=True, max_length=30, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('error', 'error')], default='pending', max_length=30)),
                ('reference_token', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charge_foloosi', to='django_banking.Operation')),
            ],
            options={
                'db_table': 'django_banking_foloosicharge',
            },
        ),
    ]
