# Generated by Django 3.0.3 on 2020-03-15 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foloosi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foloosicharge',
            options={'ordering': ['-created_at']},
        ),
    ]
