# Generated by Django 3.0.3 on 2020-03-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foloosi', '0002_auto_20200315_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foloosicharge',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('error', 'error'), ('refund', 'refund')], default='pending', max_length=30),
        ),
    ]
