# Generated by Django 3.0.3 on 2020-03-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foloosi', '0003_auto_20200317_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foloosicharge',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'error'), ('refund', 'refund')], default='pending', max_length=30),
        ),
    ]
