# Generated by Django 2.2.2 on 2020-01-13 10:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_banking', '0002_auto_20200113_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('slug', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('common_shares', 'Common shares'), ('convertible_debt', 'Convertible bond')], max_length=32, verbose_name='type')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='django_banking.Asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='securities', to='campaigns.Company')),
            ],
            options={
                'verbose_name': 'Security',
                'verbose_name_plural': 'Securities',
            },
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('limit_max_share', models.PositiveIntegerField(blank=True, null=True, verbose_name='max investment amount per user')),
                ('limit_min_share', models.PositiveIntegerField(default=1, verbose_name='min investment amount per user')),
                ('date_start', models.DateTimeField(verbose_name='campaign starts time')),
                ('date_end', models.DateTimeField(verbose_name='deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valuation', models.DecimalField(decimal_places=2, help_text='Valuation must be same across all campaign rounds.', max_digits=16, verbose_name='valuation')),
                ('goal', models.DecimalField(decimal_places=2, help_text='Cannot be grater then valuation', max_digits=16, verbose_name='Round size')),
                ('round', models.CharField(choices=[('angel', 'Angel'), ('seed', 'Seed'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=32, verbose_name='Round name')),
                ('shares', models.PositiveIntegerField(verbose_name='Total number of shares')),
                ('price', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Single share price')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('clearing', 'Clearing'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=16)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.Security')),
            ],
            options={
                'verbose_name': 'Fundraising offering',
                'verbose_name_plural': 'Fundraising offerings',
                'ordering': ['-created_at'],
            },
        ),
    ]
