# Generated by Django 2.2.2 on 2020-01-13 11:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 1, 13, 11, 6, 11, 966413, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='security',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='type',
            field=models.CharField(choices=[('common_shares', 'Common shares'), ('convertible_debt', 'Convertible bond')], help_text='Once created, type cannot be changed anymore.', max_length=32, verbose_name='type'),
        ),
    ]
