# Generated by Django 2.2.2 on 2020-01-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_auto_20200113_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='security',
            name='type',
            field=models.CharField(choices=[('common_shares', 'Common shares'), ('convertible_debt', 'Convertible bond')], default='common_shares', help_text='Once created, type cannot be changed anymore.', max_length=32, verbose_name='type'),
        ),
    ]
