# Generated by Django 2.2.2 on 2020-01-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_auto_20200113_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.CharField(help_text='Should be identical to the CMS slug', max_length=64, unique=True),
        ),
    ]
