# Generated by Django 2.2.2 on 2020-01-14 11:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20200114_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offering',
            name='limit_max_share',
        ),
        migrations.RemoveField(
            model_name='offering',
            name='limit_min_share',
        ),
        migrations.AddField(
            model_name='offering',
            name='limit_max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='max investment amount per user'),
        ),
        migrations.AddField(
            model_name='offering',
            name='limit_min_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=16, verbose_name='min investment amount per user'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Single share price'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='shares',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total number of shares'),
        ),
    ]
