# Generated by Django 3.0.3 on 2020-02-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_auto_20200114_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='type',
            field=models.CharField(choices=[('common_shares', 'Common shares'), ('convertible_debt', 'Convertible bond'), ('preferred_shares', 'Preferred Shares')], default='common_shares', help_text='Once created, type cannot be changed anymore.', max_length=32, verbose_name='type'),
        ),
    ]
