# Generated by Django 3.0.3 on 2020-02-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_auto_20200206_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('waitlist', 'Wait list'), ('active', 'Active'), ('clearing', 'Clearing'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='draft', max_length=16),
        ),
    ]
