# Generated by Django 3.0.3 on 2020-02-11 07:58

from django.db import migrations

from jibrel.campaigns.enum import OfferingStatus


def fix_status(apps, schema_editor):
    Offering = apps.get_model('campaigns', 'Offering')
    Offering.objects.filter(
        status='pending'
    ).select_for_update().update(
        status=OfferingStatus.DRAFT
    )


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_auto_20200210_1028'),
    ]

    operations = [
        migrations.RunPython(fix_status)
    ]
