# Generated by Django 2.2.2 on 2020-01-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('fiat', 'Fiat'), ('crypto', 'Cryptocurrency'), ('token', 'Token')], max_length=10),
        ),
    ]
