# Generated by Django 2.2.2 on 2020-01-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_banking', '0002_auto_20200113_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
