# Generated by Django 2.2.2 on 2020-01-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_banking', '0003_auto_20200113_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('buy', 'Buy'), ('sell', 'Sell'), ('correction', 'Correction'), ('refund', 'Refund')], db_index=True, max_length=10),
        ),
    ]
