# Generated by Django 3.0.3 on 2020-02-07 12:09

from django.db import migrations
from django.db.models import F

from django_banking.models.transactions.enum import OperationType


def fix_references(apps, schema_editor):
    Operation = apps.get_model('django_banking', 'Operation')
    qs = Operation.objects.filter(
        type=OperationType.REFUND,
        references__deposit_id__isnull=False
    )
    for obj in qs:
        obj.references = {
            'deposit_id': obj.references['deposit_id'],
            'deposit': obj.references['deposit_id']

        }
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('django_banking', '0004_auto_20200120_1220'),
    ]

    operations = [
        migrations.RunPython(fix_references)
    ]
