# Generated by Django 3.0.3 on 2020-03-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_banking', '0005_auto_20200207_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='method',
            field=models.CharField(choices=[('card', 'Card'), ('wire_transfer', 'Wire Transfer'), ('digital', 'Digital'), ('other', 'Other')], db_index=True, default='other', max_length=16),
        ),
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('action_required', 'Action required'), ('hold', 'On hold'), ('committed', 'Committed'), ('cancelled', 'Cancelled'), ('deleted', 'Deleted'), ('failed', 'Failed')], db_index=True, default='new', max_length=16),
        ),
    ]
