# Generated by Django 2.2.2 on 2020-01-14 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_banking', '0003_auto_20200113_1135'),
        ('campaigns', '0004_auto_20200114_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('hold', 'Hold'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_banking.UserAccount')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='campaigns.Offering')),
            ],
        ),
    ]
