# Generated by Django 2.2.2 on 2020-01-14 13:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentapplication',
            name='shares',
        ),
        migrations.AddField(
            model_name='investmentapplication',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentapplication',
            name='references',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('hold', 'Hold'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('error', 'Error')], default='pending', max_length=16),
        ),
    ]
