# Generated by Django 2.2.2 on 2020-01-15 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.DJANGO_BANKING_USER_MODEL),
        ('django_banking', '0003_auto_20200113_1135'),
        ('investment', '0002_auto_20200114_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentapplication',
            name='references',
        ),
        migrations.AddField(
            model_name='investmentapplication',
            name='deposit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_banking.Operation'),
        ),
        migrations.AddField(
            model_name='investmentapplication',
            name='is_agreed_risks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentapplication',
            name='is_agreed_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentapplication',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.DJANGO_BANKING_USER_MODEL),
            preserve_default=False,
        ),
    ]
