# Generated by Django 2.2.2 on 2020-01-15 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_auto_20200115_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentapplication',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_banking.Account'),
        ),
    ]
