# Generated by Django 2.2.2 on 2020-01-16 14:19

from django.db import migrations, models
import django_banking.utils


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_auto_20200115_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentapplication',
            name='deposit_reference_code',
            field=models.CharField(default=django_banking.utils.generate_deposit_reference_code, max_length=100),
        ),
    ]
