# Generated by Django 2.2.2 on 2020-01-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0005_investmentapplication_deposit_reference_code'),
        ('investment', '0005_auto_20200116_1818'),
    ]

    operations = [
    ]
