# Generated by Django 2.2.2 on 2020-01-20 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_banking', '0004_auto_20200120_1220'),
        ('investment', '0006_merge_20200117_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentapplication',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='investmentapplication',
            name='refund',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunded_application', to='django_banking.Operation'),
        ),
        migrations.AlterField(
            model_name='investmentapplication',
            name='deposit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposited_application', to='django_banking.Operation'),
        ),
    ]
