# Generated by Django 2.2.2 on 2020-01-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0007_auto_20200120_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentapplication',
            name='refund',
        ),
    ]
