# Generated by Django 2.2.3 on 2020-01-29 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_banking.storages


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_auto_20200114_1139'),
        ('investment', '0007_auto_20200120_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django_banking.storages.AmazonS3Storage(location='persoanl_agreements'), upload_to='')),
                ('is_agreed', models.BooleanField(default=False)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.Offering')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.DJANGO_BANKING_USER_MODEL)),
            ],
        ),
    ]
