# Generated by Django 2.2.3 on 2020-01-30 11:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_auto_20200114_1139'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investment', '0008_personalagreement'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personalagreement',
            unique_together={('offering', 'user')},
        ),
    ]
