# Generated by Django 3.0 on 2020-01-30 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0009_auto_20200130_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentapplication',
            name='refund',
        ),
    ]
