# Generated by Django 3.0 on 2020-01-30 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0008_remove_investmentapplication_refund'),
        ('investment', '0009_auto_20200130_1111'),
    ]

    operations = [
    ]
