# Generated by Django 3.0.3 on 2020-02-06 15:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0010_merge_20200130_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentapplication',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4(), editable=False),
        ),
        migrations.AddField(
            model_name='personalagreement',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4(), editable=False),
        ),
    ]
