# Generated by Django 3.0.3 on 2020-02-06 16:00
import uuid
from django.db import migrations

def create_uuid(apps, schema_editor):
    InvestmentApplication = apps.get_model('investment', 'InvestmentApplication')
    PersonalAgreement = apps.get_model('investment', 'PersonalAgreement')
    for obj in InvestmentApplication.objects.all():
        obj.uuid = uuid.uuid4()
        obj.save()

    for obj in PersonalAgreement.objects.all():
        obj.uuid = uuid.uuid4()
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0011_auto_20200206_1557'),
    ]

    operations = [
        migrations.RunPython(create_uuid),
    ]
