# Generated by Django 3.0.3 on 2020-02-06 16:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0012_auto_20200206_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentapplication',
            name='id',
        ),
        migrations.RemoveField(
            model_name='personalagreement',
            name='id',
        ),
        migrations.AlterField(
            model_name='investmentapplication',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personalagreement',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
