# Generated by Django 3.0.3 on 2020-02-10 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0007_auto_20200210_1028'),
        ('investment', '0013_auto_20200206_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentSubscription',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribes', to='campaigns.Offering')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscribes', to='authentication.User')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
