# Generated by Django 3.0.3 on 2020-02-10 15:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0007_auto_20200210_1028'),
        ('investment', '0014_investmentsubscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investmentsubscription',
            unique_together={('user', 'offering')},
        ),
    ]
