# Generated by Django 3.0.3 on 2020-02-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0015_auto_20200210_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentsubscription',
            name='amount',
            field=models.CharField(choices=[('USD 1,000 - 9,999', 'USD 1,000 - 9,999'), ('USD 10,000 - 19,999', 'USD 10,000 - 19,999'), ('USD 20,000 - 49,999', 'USD 20,000 - 49,999'), ('USD 50,000 - 99,999', 'USD 50,000 - 99,999'), ('USD 100,000 +', 'USD 100,000 +')], max_length=30),
        ),
    ]
