# Generated by Django 3.0.3 on 2020-02-11 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_auto_20200211_0758'),
        ('wire_transfer', '0005_auto_20200204_1613'),
        ('investment', '0015_auto_20200210_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentapplication',
            name='is_agreed_subscription',
        ),
        migrations.AddField(
            model_name='investmentapplication',
            name='bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wire_transfer.ColdBankAccount'),
        ),
        migrations.AddField(
            model_name='investmentapplication',
            name='subscription_agreement_status',
            field=models.CharField(choices=[('initial', 'Initial'), ('preparing', 'Preparing'), ('prepared', 'Prepared'), ('validating', 'Validating'), ('success', 'Success'), ('error', 'Error')], default='initial', max_length=16),
        ),
        migrations.AlterField(
            model_name='investmentapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('hold', 'Hold'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('error', 'Error')], default='pending', max_length=16),
        ),
        migrations.CreateModel(
            name='SubscriptionAgreementTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=320)),
                ('template_id', models.UUIDField()),
                ('is_active', models.BooleanField(default=True)),
                ('offering', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.Offering')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envelope_id', models.UUIDField()),
                ('envelope_status', models.CharField(choices=[('completed', 'Completed'), ('created', 'Created'), ('declined', 'Declined'), ('delivered', 'Delivered'), ('sent', 'Sent'), ('signed', 'Signed'), ('voided', 'Voided')], max_length=20)),
                ('request_id', models.UUIDField()),
                ('redirect_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='agreement', to='investment.InvestmentApplication')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='investment.SubscriptionAgreementTemplate')),
            ],
        ),
        migrations.AddConstraint(
            model_name='subscriptionagreementtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(is_active=True), fields=('offering',), name='unique_active_for_offering'),
        ),
    ]
