# Generated by Django 3.0.3 on 2020-02-11 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wire_transfer', '0005_auto_20200204_1613'),
        ('investment', '0017_fill_bank_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentapplication',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wire_transfer.ColdBankAccount'),
        ),
    ]
