# Generated by Django 3.0.3 on 2020-02-11 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0018_auto_20200211_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionagreement',
            name='request_id',
        ),
    ]
