# Generated by Django 3.0.3 on 2020-02-13 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0016_auto_20200213_1157'),
        ('investment', '0019_remove_subscriptionagreement_request_id'),
    ]

    operations = [
    ]
