# Generated by Django 3.0.3 on 2020-02-18 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0020_merge_20200213_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionagreement',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='investment.InvestmentApplication'),
        ),
    ]
