# Generated by Django 3.0.3 on 2020-03-04 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wire_transfer', '0005_auto_20200204_1613'),
        ('investment', '0021_auto_20200218_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentapplication',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wire_transfer.ColdBankAccount'),
        ),
    ]
